FROM osrf/ros:melodic-desktop-full-bionic

RUN apt update
RUN apt upgrade -y
RUN apt install wget -y
RUN apt install liburdfdom-tools -y

RUN apt install -y terminator
RUN mkdir -p /root/.config/terminator
RUN touch /root/.config/terminator/config

RUN apt install ros-melodic-husky-navigation ros-melodic-husky-gazebo ros-melodic-husky-viz -y

